import "dotenv/config";import express from "express";import fs from "fs";import path from "path";
const app=express(),PORT=process.env.PORT||3000,ROOT=process.cwd(),TOKEN=process.env.AGENT_TOKEN||"change-this-token",READY=process.env.SHIPSTATION_READY_TAG||"Ready For Production",INPROD=process.env.SHIPSTATION_IN_PRODUCTION_TAG||"In Production",FILE=path.join(ROOT,"shipstation.mock.json"),ART=path.join(ROOT,"artwork");
let orders=[],pieces=[],jobs=[],events=[],counter=14540600;app.use(express.json());app.use(express.static("public"));app.use("/artwork",express.static(ART));
const read=()=>JSON.parse(fs.readFileSync(FILE,"utf8"));const write=x=>fs.writeFileSync(FILE,JSON.stringify(x,null,2));const pid=()=>String(++counter);const log=(o,p,m)=>events.unshift({at:new Date().toISOString(),orderNumber:o,pieceId:p,message:m});const findP=id=>pieces.find(p=>p.pieceId===String(id));const findO=id=>orders.find(o=>o.orderNumber===id);
function recalc(orderNumber){const o=findO(orderNumber);if(!o)return;const ps=pieces.filter(p=>p.orderNumber===orderNumber&&!p.isSuperseded);const done=ps.length&&ps.every(p=>["qc_passed","shipped"].includes(p.status));o.binStatus=done?"complete_ready_for_shipping":"incomplete";o.productionStatus=done?"qc_complete":ps.some(p=>["queued","sent_to_graphics_lab","printed","cured"].includes(p.status))?"in_production":ps.some(p=>p.status==="rejected")?"reprint_needed":"imported";}
app.get('/api/shipstation/ready',(q,s)=>s.json(read().filter(o=>o.tags.includes(READY))));
app.post('/api/import/ready',(q,s)=>{let rows=read(),ready=rows.filter(o=>o.tags.includes(READY)),batch=`BATCH-${new Date().toISOString().slice(0,10)}`;for(const src of ready){src.tags=src.tags.filter(t=>t!==READY);if(!src.tags.includes(INPROD))src.tags.push(INPROD);if(findO(src.orderNumber))continue;orders.push({orderNumber:src.orderNumber,customer:src.customer,store:src.store,rush:src.rush,batchId:batch,productionStatus:'imported',binStatus:'incomplete'});for(const item of src.items)for(let unit=1;unit<=item.qty;unit++)for(const step of item.steps){const p={pieceId:pid(),orderNumber:src.orderNumber,batchId:batch,lineItemId:item.lineItemId,unitNumber:unit,unitCount:item.qty,sku:item.sku,title:item.title,garment:item.garment,color:item.color,size:item.size,vendorSku:item.vendorSku,productType:step.productType,location:step.location,artworkFile:step.artworkFile,artworkUrl:`/artwork/${step.artworkFile}`,printer:step.printer,pretreat:step.pretreat,whiteInk:step.whiteInk,status:'created',isReprint:false,isSuperseded:false};pieces.push(p);log(src.orderNumber,p.pieceId,`Created ${p.productType} ${p.location} piece`)}log(src.orderNumber,null,`Imported and tagged ${INPROD}`)}write(rows);s.json({success:true,message:`Imported ${ready.length} orders and created ${pieces.length} pieces.`})});
app.get('/api/orders',(q,s)=>s.json(orders.map(o=>({...o,pieces:pieces.filter(p=>p.orderNumber===o.orderNumber&&!p.isSuperseded)}))));app.get('/api/order/:id',(q,s)=>{const o=findO(q.params.id);if(!o)return s.status(404).json({error:'Order not found'});s.json({...o,pieces:pieces.filter(p=>p.orderNumber===o.orderNumber)})});app.get('/api/pieces',(q,s)=>s.json(pieces));app.get('/api/piece/:id',(q,s)=>{const p=findP(q.params.id);if(!p)return s.status(404).json({error:'Piece not found'});s.json({piece:p,order:findO(p.orderNumber)})});
app.get('/api/reports/garments',(q,s)=>{const m=new Map();for(const p of pieces.filter(p=>!p.isSuperseded)){const uk=`${p.lineItemId}-${p.unitNumber}`;if([...m.values()].some(x=>x.unitKey===uk))continue;const k=p.vendorSku;if(!m.has(k))m.set(k,{unitKey:uk,vendorSku:k,garment:p.garment,color:p.color,size:p.size,qty:0});m.get(k).qty++}s.json([...m.values()].map(({unitKey,...r})=>r))});
app.post('/api/piece/:id/send',(q,s)=>{const p=findP(q.params.id);if(!p)return s.status(404).json({error:'Piece not found'});if(!fs.existsSync(path.join(ART,p.artworkFile)))return s.status(404).json({error:'Artwork missing'});p.status='queued';const j={id:`JOB-${Date.now()}-${p.pieceId}`,pieceId:p.pieceId,orderNumber:p.orderNumber,status:'queued',printer:p.printer,artworkFile:p.artworkFile,artworkUrl:p.artworkUrl};jobs.push(j);recalc(p.orderNumber);log(p.orderNumber,p.pieceId,`Queued to ${p.printer}`);s.json({success:true,message:`Piece ${p.pieceId} queued`,job:j})});
app.post('/api/piece/:id/status',(q,s)=>{const p=findP(q.params.id);if(!p)return s.status(404).json({error:'Piece not found'});p.status=q.body.status;recalc(p.orderNumber);log(p.orderNumber,p.pieceId,`Marked ${p.status}`);s.json({success:true,piece:p})});
app.post('/api/piece/:id/reject',(q,s)=>{const p=findP(q.params.id);if(!p)return s.status(404).json({error:'Piece not found'});p.status='rejected';p.isSuperseded=true;const r={...p,pieceId:pid(),status:'created',isReprint:true,isSuperseded:false,originalPieceId:p.pieceId,reprintReason:q.body.reason||'QC Reject'};pieces.push(r);recalc(p.orderNumber);log(p.orderNumber,p.pieceId,'Rejected');log(r.orderNumber,r.pieceId,`Replacement for ${p.pieceId}`);s.json({success:true,message:`Created replacement ${r.pieceId}`,replacement:r})});
app.post('/api/order/:id/ship',(q,s)=>{const o=findO(q.params.id);if(!o)return s.status(404).json({error:'Order not found'});const ps=pieces.filter(p=>p.orderNumber===o.orderNumber&&!p.isSuperseded);if(!ps.length||!ps.every(p=>p.status==='qc_passed'))return s.status(400).json({error:'All active pieces must pass QC'});ps.forEach(p=>p.status='shipped');o.productionStatus='shipped';o.binStatus='shipped';s.json({success:true})});app.get('/api/events',(q,s)=>s.json(events));
app.get('/api/agent/jobs',(q,s)=>q.query.token!==TOKEN?s.status(401).json({error:'Unauthorized'}):s.json(jobs.filter(j=>j.status==='queued')));app.post('/api/agent/jobs/:id/complete',(q,s)=>{if(q.query.token!==TOKEN)return s.status(401).json({error:'Unauthorized'});const j=jobs.find(x=>x.id===q.params.id);if(!j)return s.status(404).json({error:'Job not found'});j.status='sent_to_graphics_lab';const p=findP(j.pieceId);if(p)p.status='sent_to_graphics_lab';s.json({success:true})});app.listen(PORT,()=>console.log(`ProductionOS v2 on ${PORT}`));